#spring.application.name=Project_two

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_db
    driver-class-name: org.postgresql.Driver
    username: car
    password: car
  flyway:
    enabled: true
    locations: classpath:db.migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080
